# Generated by Django 2.2 on 2024-12-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20241210_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
