# Generated by Django 2.2 on 2024-12-11 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20241210_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='budgetcategory',
            name='monthly_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
