# Generated by Django 2.2 on 2024-12-11 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0008_auto_20241210_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='monthly_income',
        ),
    ]
